import bpy
import json
import re


ACTION_TYPE_PRESETS = (
    "PlayEffect",
    "OpenDoor",
    "EnableObject",
    "DisableObject",
    "SpawnEnemy",
    "StartDialogue",
    "MoveObject",
    "StartCameraRail",
    "PlayPostEffect",
    "Custom",
)

ACTION_TYPE_DISPLAY_NAMES = {
    "PlayEffect": "エフェクト再生 (PlayEffect)",
    "OpenDoor": "扉を開く (OpenDoor)",
    "EnableObject": "オブジェクト有効化 (EnableObject)",
    "DisableObject": "オブジェクト無効化 (DisableObject)",
    "SpawnEnemy": "敵を出現 (SpawnEnemy)",
    "StartDialogue": "会話開始 (StartDialogue)",
    "MoveObject": "オブジェクト移動 (MoveObject)",
    "StartCameraRail": "カメラレール開始 (StartCameraRail)",
    "PlayPostEffect": "ポストエフェクト再生 (PlayPostEffect)",
    "Custom": "カスタム処理 (Custom)",
}

POST_EFFECT_TYPE_PRESETS = (
    "Flash",
    "Grayscale",
    "FadeBlack",
    "DamageVignette",
    "Noise",
    "ChromaticAberration",
    "Custom",
)

POST_EFFECT_TYPE_DISPLAY_NAMES = {
    "Flash": "画面フラッシュ (Flash)",
    "Grayscale": "グレースケール (Grayscale)",
    "FadeBlack": "黒フェード (FadeBlack)",
    "DamageVignette": "ダメージビネット (DamageVignette)",
    "Noise": "ノイズ (Noise)",
    "ChromaticAberration": "色収差 (ChromaticAberration)",
    "Custom": "カスタム (Custom)",
}

_is_syncing_actions = False


def _make_default_flag_id(obj):
    safe_name = re.sub(r"\W+", "_", obj.name).strip("_")
    if not safe_name:
        safe_name = "Object"
    return f"flag_{safe_name}"


def _set_default(obj, key, value):
    if key not in obj:
        obj[key] = value


def _update_property_ui(obj, key, description):
    try:
        obj.id_properties_ui(key).update(description=description)
    except Exception:
        pass


def _to_string(value, default=""):
    if value is None:
        return default
    return str(value)


def _normalize_action(action):
    if not isinstance(action, dict):
        return None
    return {
        "targetObjectId": _to_string(action.get("targetObjectId", action.get("target_object_id", ""))),
        "targetObjectName": _to_string(action.get("targetObjectName", action.get("target_object_name", ""))),
        "actionType": _to_string(action.get("actionType", action.get("action_type", "PlayEffect")), "PlayEffect"),
        "actionDescription": _to_string(
            action.get("actionDescription", action.get("action_description", ""))),
        "postEffectType": _to_string(
            action.get("postEffectType", action.get("post_effect_type", "Flash")), "Flash"),
    }


def _parse_event_object_actions(value):
    if value is None:
        return []

    if isinstance(value, str):
        text = value.strip()
        if not text:
            return []
        if text.startswith("[") or text.startswith("{"):
            try:
                loaded = json.loads(text)
                if isinstance(loaded, dict):
                    loaded = [loaded]
                if isinstance(loaded, list):
                    return [
                        action for action in (_normalize_action(item) for item in loaded)
                        if action is not None
                    ]
            except json.JSONDecodeError as error:
                print(f"[LevelEditor] event_object_actions UI JSON parse failed: {error}")

        actions = []
        for item in text.split(";"):
            parts = [part.strip() for part in item.split("|")]
            if not parts or not parts[0]:
                continue
            actions.append({
                "targetObjectId": "",
                "targetObjectName": parts[0],
                "actionType": parts[1] if len(parts) > 1 and parts[1] else "PlayEffect",
                "actionDescription": parts[2] if len(parts) > 2 else "",
                "postEffectType": parts[3] if len(parts) > 3 and parts[3] else "Flash",
            })
        return actions

    if isinstance(value, list):
        return [
            action for action in (_normalize_action(item) for item in value)
            if action is not None
        ]

    return []


def _action_collection_available(obj):
    return obj is not None and hasattr(obj, "level_event_object_actions")


def _sync_custom_property_from_collection(obj):
    if _is_syncing_actions or not _action_collection_available(obj):
        return

    actions = []
    for item in obj.level_event_object_actions:
        actions.append({
            "targetObjectId": item.target_object_id.strip(),
            "targetObjectName": item.target_object_name.strip(),
            "actionType": item.action_type.strip() or "Custom",
            "actionDescription": item.action_description.strip(),
            "postEffectType": item.post_effect_type.strip() or "Flash",
        })
    obj["event_object_actions"] = json.dumps(actions, ensure_ascii=False) if actions else ""
    _update_property_ui(
        obj,
        "event_object_actions",
        "JSON ObjectAction list generated by Event Flag Editor UI")


def _sync_collection_from_custom_property(obj):
    global _is_syncing_actions
    if not _action_collection_available(obj):
        return

    actions = _parse_event_object_actions(obj.get("event_object_actions", ""))
    _is_syncing_actions = True
    try:
        obj.level_event_object_actions.clear()
        for action in actions:
            item = obj.level_event_object_actions.add()
            item.target_object_id = action.get("targetObjectId", "")
            item.target_object_name = action.get("targetObjectName", "")
            item.action_type = action.get("actionType", "PlayEffect") or "PlayEffect"
            item.action_description = action.get("actionDescription", "")
            item.post_effect_type = action.get("postEffectType", "Flash") or "Flash"

        if obj.level_event_object_action_index >= len(obj.level_event_object_actions):
            obj.level_event_object_action_index = max(0, len(obj.level_event_object_actions) - 1)
    finally:
        _is_syncing_actions = False


def _ensure_action_collection_initialized(obj):
    if not _action_collection_available(obj):
        return
    raw_actions = obj.get("event_object_actions", "")
    if len(obj.level_event_object_actions) == 0 and isinstance(raw_actions, str) and raw_actions.strip():
        _sync_collection_from_custom_property(obj)


def _on_event_object_action_changed(self, context):
    obj = self.id_data
    if obj is not None:
        _sync_custom_property_from_collection(obj)


class MYADDON_PG_event_object_action(bpy.types.PropertyGroup):
    target_object_name: bpy.props.StringProperty(
        name="対象オブジェクト名 (Target Object Name)",
        default="",
        update=_on_event_object_action_changed)
    target_object_id: bpy.props.StringProperty(
        name="対象オブジェクトID (Target Object ID)",
        default="",
        update=_on_event_object_action_changed)
    action_type: bpy.props.StringProperty(
        name="アクション種類 (Action Type)",
        default="PlayEffect",
        update=_on_event_object_action_changed)
    action_description: bpy.props.StringProperty(
        name="アクション説明 (Action Description)",
        default="",
        update=_on_event_object_action_changed)
    post_effect_type: bpy.props.StringProperty(
        name="ポストエフェクト種類 (Post Effect Type)",
        default="Flash",
        update=_on_event_object_action_changed)


def ensure_editor_properties(obj):
    object_id = obj.get("object_id", obj.name)
    obj["object_id"] = object_id
    _set_default(obj, "editor_label", obj.name)
    _set_default(obj, "editor_description", "")
    _update_property_ui(obj, "object_id", "Stable object ID used by Level Editor links")
    _update_property_ui(obj, "editor_label", "Editor display label")
    _update_property_ui(obj, "editor_description", "Editor description")


def ensure_event_flag_properties(obj):
    ensure_editor_properties(obj)
    object_id = obj.get("object_id", obj.name)
    flag_id = obj.get("event_flag_id", _make_default_flag_id(obj))

    obj["object_id"] = object_id
    obj["is_event_flag"] = True
    obj["event_flag_id"] = flag_id
    _set_default(obj, "event_display_name", obj.name)
    _set_default(obj, "event_description", "")
    _set_default(obj, "event_trigger_type", "PlayerEnter")
    _set_default(obj, "event_shape_type", "Box")
    _set_default(obj, "event_visible_in_editor", True)
    _set_default(obj, "event_initially_enabled", True)
    _set_default(obj, "event_one_shot", True)
    _set_default(obj, "event_next_flag_ids", "")
    _set_default(obj, "event_object_actions", "")

    _update_property_ui(obj, "event_flag_id", "Unique EventFlag ID. Example: flag_Cube")
    _update_property_ui(obj, "event_display_name", "Display name shown in editor debug UI")
    _update_property_ui(obj, "event_description", "Editor description for this EventFlag")
    _update_property_ui(obj, "event_trigger_type", "Trigger type. Example: PlayerEnter")
    _update_property_ui(obj, "event_shape_type", "Event shape: Box or Sphere")
    _update_property_ui(obj, "event_next_flag_ids", "Comma-separated next EventFlag IDs")
    _update_property_ui(obj, "event_object_actions", "Actions: target|action|description; target2|action|description")
    _ensure_action_collection_initialized(obj)
    return flag_id


class MYADDON_OT_add_event_flag_properties(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_add_event_flag_properties"
    bl_label = "イベントフラグ化 (Add Event Flag Properties)"
    bl_description = "選択中ObjectへEventFlag用の初期プロパティを追加します"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = context.object
        if obj is None:
            self.report({'WARNING'}, "No active object selected")
            return {'CANCELLED'}

        flag_id = ensure_event_flag_properties(obj)
        self.report({'INFO'}, f"EventFlag properties added: {flag_id}")
        return {'FINISHED'}


class MYADDON_OT_initialize_object_editor_info(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_initialize_object_editor_info"
    bl_label = "Object情報を初期化 (Initialize Object Editor Info)"
    bl_description = "選択中Objectへobject_id / editor_label / editor_descriptionを追加します"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = context.object
        if obj is None:
            self.report({'WARNING'}, "No active object selected")
            return {'CANCELLED'}

        ensure_editor_properties(obj)
        self.report({'INFO'}, f"Object editor info initialized: {obj.name}")
        return {'FINISHED'}


class MYADDON_OT_set_event_flag_shape(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_set_event_flag_shape"
    bl_label = "Set Event Flag Shape"
    bl_description = "EventFlagの形状をBoxまたはSphereに設定します"
    bl_options = {'REGISTER', 'UNDO'}

    shape_type: bpy.props.StringProperty(default="Box")

    def execute(self, context):
        obj = context.object
        if obj is None:
            self.report({'WARNING'}, "No active object selected")
            return {'CANCELLED'}

        ensure_event_flag_properties(obj)
        obj["event_shape_type"] = self.shape_type
        return {'FINISHED'}


class MYADDON_OT_add_event_object_action(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_add_event_object_action"
    bl_label = "アクション追加 (Add Object Action)"
    bl_description = "選択中EventFlagへObjectActionを追加します"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = context.object
        if obj is None:
            self.report({'WARNING'}, "No active object selected")
            return {'CANCELLED'}

        ensure_event_flag_properties(obj)
        if not _action_collection_available(obj):
            self.report({'ERROR'}, "ObjectAction collection is not registered")
            return {'CANCELLED'}

        _ensure_action_collection_initialized(obj)
        item = obj.level_event_object_actions.add()
        item.target_object_name = ""
        item.target_object_id = ""
        item.action_type = "PlayEffect"
        item.action_description = ""
        item.post_effect_type = "Flash"
        obj.level_event_object_action_index = len(obj.level_event_object_actions) - 1
        _sync_custom_property_from_collection(obj)
        return {'FINISHED'}


class MYADDON_OT_remove_event_object_action(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_remove_event_object_action"
    bl_label = "アクション削除 (Remove Object Action)"
    bl_description = "選択中EventFlagからObjectActionを削除します"
    bl_options = {'REGISTER', 'UNDO'}

    index: bpy.props.IntProperty(default=-1)

    def execute(self, context):
        obj = context.object
        if obj is None or not _action_collection_available(obj):
            self.report({'WARNING'}, "No EventFlag ObjectAction collection")
            return {'CANCELLED'}

        _ensure_action_collection_initialized(obj)
        index = self.index if self.index >= 0 else obj.level_event_object_action_index
        if index < 0 or index >= len(obj.level_event_object_actions):
            self.report({'WARNING'}, "ObjectAction index is out of range")
            return {'CANCELLED'}

        obj.level_event_object_actions.remove(index)
        obj.level_event_object_action_index = min(index, max(0, len(obj.level_event_object_actions) - 1))
        _sync_custom_property_from_collection(obj)
        return {'FINISHED'}


class MYADDON_OT_set_event_object_action_type(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_set_event_object_action_type"
    bl_label = "アクション種類を設定 (Set Action Type)"
    bl_description = "ObjectActionのアクション種類を候補から設定します"
    bl_options = {'REGISTER', 'UNDO'}

    index: bpy.props.IntProperty(default=-1)
    action_type: bpy.props.StringProperty(default="PlayEffect")

    def execute(self, context):
        obj = context.object
        if obj is None or not _action_collection_available(obj):
            self.report({'WARNING'}, "No EventFlag ObjectAction collection")
            return {'CANCELLED'}

        _ensure_action_collection_initialized(obj)
        if self.index < 0 or self.index >= len(obj.level_event_object_actions):
            self.report({'WARNING'}, "ObjectAction index is out of range")
            return {'CANCELLED'}

        obj.level_event_object_actions[self.index].action_type = self.action_type
        _sync_custom_property_from_collection(obj)
        return {'FINISHED'}


class MYADDON_OT_set_event_object_action_post_effect_type(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_set_event_object_action_post_effect_type"
    bl_label = "ポストエフェクト種類を設定 (Set Post Effect Type)"
    bl_description = "ObjectActionのpostEffectTypeを候補から設定します"
    bl_options = {'REGISTER', 'UNDO'}

    index: bpy.props.IntProperty(default=-1)
    post_effect_type: bpy.props.StringProperty(default="Flash")

    def execute(self, context):
        obj = context.object
        if obj is None or not _action_collection_available(obj):
            self.report({'WARNING'}, "No EventFlag ObjectAction collection")
            return {'CANCELLED'}

        _ensure_action_collection_initialized(obj)
        if self.index < 0 or self.index >= len(obj.level_event_object_actions):
            self.report({'WARNING'}, "ObjectAction index is out of range")
            return {'CANCELLED'}

        obj.level_event_object_actions[self.index].post_effect_type = self.post_effect_type
        _sync_custom_property_from_collection(obj)
        return {'FINISHED'}


class MYADDON_OT_load_event_object_actions_from_raw(bpy.types.Operator):
    bl_idname = "myaddon.myaddon_ot_load_event_object_actions_from_raw"
    bl_label = "RawからObjectActionを読込 (Load Object Actions From Raw)"
    bl_description = "event_object_actions文字列をObjectAction編集UIへ読み込みます"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = context.object
        if obj is None or not _action_collection_available(obj):
            self.report({'WARNING'}, "No EventFlag ObjectAction collection")
            return {'CANCELLED'}

        _sync_collection_from_custom_property(obj)
        self.report({'INFO'}, "ObjectAction UI loaded from event_object_actions")
        return {'FINISHED'}


def _draw_custom_property(layout, obj, key, text):
    try:
        if key in obj:
            layout.prop(obj, f'["{key}"]', text=text)
            return True
        row = layout.row()
        row.enabled = False
        row.label(text=f"{text}: (未設定)")
        return False
    except Exception as error:
        layout.label(text=f"{text}: 表示エラー")
        layout.label(text=str(error)[:96])
        print(f"[LevelEditor] draw custom property failed: {key}: {error}")
        return False


def _draw_editor_properties(layout, obj):
    box = layout.box()
    box.label(text="Object情報 (Object Editor Info)")
    box.operator(
        MYADDON_OT_initialize_object_editor_info.bl_idname,
        text="Object情報を初期化 (Initialize Object Editor Info)",
        icon='PRESET')
    _draw_custom_property(box, obj, "object_id", "オブジェクトID (object_id)")
    _draw_custom_property(box, obj, "editor_label", "エディタ表示名 (Editor Label)")
    _draw_custom_property(box, obj, "editor_description", "エディタ説明 (Editor Description)")


def _draw_action_type_presets(layout, index):
    row = layout.row(align=True)
    for preset in ACTION_TYPE_PRESETS[:4]:
        op = row.operator(
            MYADDON_OT_set_event_object_action_type.bl_idname,
            text=ACTION_TYPE_DISPLAY_NAMES.get(preset, preset))
        op.index = index
        op.action_type = preset
    row = layout.row(align=True)
    for preset in ACTION_TYPE_PRESETS[4:]:
        op = row.operator(
            MYADDON_OT_set_event_object_action_type.bl_idname,
            text=ACTION_TYPE_DISPLAY_NAMES.get(preset, preset))
        op.index = index
        op.action_type = preset


def _draw_post_effect_type_presets(layout, index):
    row = layout.row(align=True)
    for preset in POST_EFFECT_TYPE_PRESETS[:3]:
        op = row.operator(
            MYADDON_OT_set_event_object_action_post_effect_type.bl_idname,
            text=POST_EFFECT_TYPE_DISPLAY_NAMES.get(preset, preset))
        op.index = index
        op.post_effect_type = preset
    row = layout.row(align=True)
    for preset in POST_EFFECT_TYPE_PRESETS[3:]:
        op = row.operator(
            MYADDON_OT_set_event_object_action_post_effect_type.bl_idname,
            text=POST_EFFECT_TYPE_DISPLAY_NAMES.get(preset, preset))
        op.index = index
        op.post_effect_type = preset


def _draw_object_actions(layout, obj):
    box = layout.box()
    box.label(text="=== 対象オブジェクトへの処理設定 (Object Actions) ===")
    box.label(text="このイベントフラグが発動した時に、対象Objectへ何をするかを設定します")
    box.label(text="赤線は EventFlag から対象Object への影響関係を表します")
    action_row = box.row(align=True)
    action_row.operator(MYADDON_OT_add_event_object_action.bl_idname, text="アクション追加 (Add Object Action)", icon='ADD')
    action_row.operator(
        MYADDON_OT_load_event_object_actions_from_raw.bl_idname,
        text="Rawから読込 (Load Raw)",
        icon='FILE_REFRESH')

    if not _action_collection_available(obj):
        box.label(text="ObjectAction UI property is not registered")
        _draw_custom_property(box, obj, "event_object_actions", "event_object_actions")
        return

    if len(obj.level_event_object_actions) == 0:
        box.label(text="ObjectActionは未設定です")
        box.label(text="例: EffectSpawn_01 / PlayEffect / パーティクルを再生する")
        box.label(text="例: rail_main_01 / StartCameraRail / カメラをメインレールに乗せる")

    for index, action in enumerate(obj.level_event_object_actions):
        action_box = box.box()
        row = action_box.row(align=True)
        row.label(text=f"処理 {index + 1} (Action {index + 1})")
        remove = row.operator(MYADDON_OT_remove_event_object_action.bl_idname, text="アクション削除 (Remove Object Action)", icon='REMOVE')
        remove.index = index

        action_box.label(text="例: EffectSpawn_01")
        action_box.label(text="対象Objectの名前を入れると赤線で接続されます")
        action_box.label(text="StartCameraRailの場合はRail IDまたはRail名を入力します")
        action_box.prop(action, "target_object_name", text="対象オブジェクト名 (Target Object Name)")
        action_box.prop(action, "target_object_id", text="対象オブジェクトID (Target Object ID)")
        action_box.prop(action, "action_type", text="実行する処理の種類 (Action Type)")
        _draw_action_type_presets(action_box, index)
        action_box.label(text="PlayPostEffectの場合に使う画面全体エフェクトです")
        action_box.prop(action, "post_effect_type", text="ポストエフェクト種類 (Post Effect Type)")
        _draw_post_effect_type_presets(action_box, index)
        action_box.prop(action, "action_description", text="画面に表示する説明文 (Action Description)")
        action_box.label(text="例: パーティクルを再生する")
        action_box.label(text="例: Door_01を開く")
        action_box.label(text="例: 敵を3体出現させる")

    raw_box = box.box()
    raw_box.label(text="互換用Raw文字列 (Raw event_object_actions)")
    _draw_custom_property(raw_box, obj, "event_object_actions", "event_object_actions")


class VIEW3D_PT_level_event_flag_editor(bpy.types.Panel):
    bl_label = "イベントフラグ編集 (Event Flag Editor)"
    bl_idname = "VIEW3D_PT_level_event_flag_editor"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "Level Editor"

    def draw(self, context):
        layout = self.layout
        obj = context.object
        if obj is None:
            layout.label(text="Objectが選択されていません")
            return

        layout.label(text=f"選択中: {obj.name}")

        action_row = layout.row()
        action_row.operator(
            MYADDON_OT_add_event_flag_properties.bl_idname,
            text="イベントフラグ化 (Add Event Flag Properties)",
            icon='BOOKMARKS')

        _draw_editor_properties(layout, obj)

        if not bool(obj.get("is_event_flag", False)):
            layout.label(text="このObjectはEventFlagではありません")
            layout.label(text="このObjectは発動対象にできます。ObjectActionはEventFlag側で設定してください。")
            layout.label(text="上のボタンでEventFlag用プロパティを追加できます")
            return

        box = layout.box()
        box.label(text="基本情報")
        _draw_custom_property(box, obj, "event_flag_id", "イベントフラグID (event_flag_id)")
        _draw_custom_property(box, obj, "event_display_name", "表示名 (event_display_name)")
        _draw_custom_property(box, obj, "event_description", "説明 (event_description)")
        _draw_custom_property(box, obj, "event_trigger_type", "トリガー種別 (event_trigger_type)")

        shape_box = layout.box()
        shape_box.label(text="形状 (event_shape_type)")
        shape_row = shape_box.row(align=True)
        op = shape_row.operator(MYADDON_OT_set_event_flag_shape.bl_idname, text="Box")
        op.shape_type = "Box"
        op = shape_row.operator(MYADDON_OT_set_event_flag_shape.bl_idname, text="Sphere")
        op.shape_type = "Sphere"
        _draw_custom_property(shape_box, obj, "event_shape_type", "現在の形状")

        state_box = layout.box()
        state_box.label(text="状態")
        _draw_custom_property(state_box, obj, "event_visible_in_editor", "エディタで表示 (event_visible_in_editor)")
        _draw_custom_property(state_box, obj, "event_initially_enabled", "初期有効 (event_initially_enabled)")
        _draw_custom_property(state_box, obj, "event_one_shot", "一回だけ発動 (event_one_shot)")

        link_box = layout.box()
        link_box.label(text="接続")
        _draw_custom_property(link_box, obj, "event_next_flag_ids", "次に有効化するフラグID一覧")
        _draw_object_actions(layout, obj)


def register_event_flag_editor_properties():
    if not hasattr(bpy.types.Object, "level_event_object_actions"):
        bpy.types.Object.level_event_object_actions = bpy.props.CollectionProperty(
            type=MYADDON_PG_event_object_action)
    if not hasattr(bpy.types.Object, "level_event_object_action_index"):
        bpy.types.Object.level_event_object_action_index = bpy.props.IntProperty(
            name="Selected ObjectAction",
            default=0,
            min=0)


def unregister_event_flag_editor_properties():
    if hasattr(bpy.types.Object, "level_event_object_action_index"):
        del bpy.types.Object.level_event_object_action_index
    if hasattr(bpy.types.Object, "level_event_object_actions"):
        del bpy.types.Object.level_event_object_actions
